generated-api/models/StacksIntrospectionCreateRequestBody.ts, generated-api/models/StacksIntrospectionsIntrospectionKeepsInner.ts, generated-api/models/StacksIntrospectionsIntrospectionProblemsInner.ts, generated-api/models/StacksIntrospectionsIntrospectionTriesInner.ts, generated-api/models/StacksIntrospectionsKeepsKeep.ts, generated-api/models/StacksIntrospectionsPloblemsPloblem.ts, generated-api/models/StacksIntrospectionsTriesTry.ts, openapi.yml
[積み上げに対する反省ができる](https://app.asana.com/0/1204548322306328/1204548322306430/f)
[積み上げの反省作成APIを作成する](https://app.asana.com/0/1204548322306328/1205119888098624/f)
https://github.com/mnmuu8/skill-climbing-frontend/pull/6 の続き
特になし
- keep, ploblem, tryの項目内容をcontentに変更した
- 特になし
- 特になし
=> keep, ploblem, tryの項目内容を表す単語を「content」に変更した

.gitignore, components/molecules/StackCard.tsx, components/molecules/StackList.tsx, components/organisms/Header.tsx, sample.ts, types/types.ts
https://app.asana.com/0/1204548322306328/1204548322306416/f
https://app.asana.com/0/1204548322306328/1205170312604096/f
特になし
特になし
- sample.tsを作成して積み上げのサンプルデータを作成した
特になし
特になし
=> sample.tsを作成して積み上げのサンプルデータを追加した

generated-api/apis/IntrospectionApi.ts, generated-api/apis/StackApi.ts, generated-api/apis/UserApi.ts, openapi.yml
[ユーザーのマイページを利用できる](https://app.asana.com/0/1204548322306328/1205170770841352/f)
[ユーザーの詳細情報を返すAPIを作成する](https://app.asana.com/0/1204548322306328/1205170770841356/f)
なし
なし
- ユーザー詳細取得のAPIを定義した
なし
なし
=> ユーザー詳細取得のAPIを定義した

README.md
[環境構築マニュアルを整備する](https://app.asana.com/0/1204548322306328/1205352883161243/f)
[FE側環境構築マニュアルを作成する](https://app.asana.com/0/1204548322306328/1205352883161382/f)
なし
なし
- FEの環境構築手順を作成した
なし
なし
=> FEの環境構築手順を作成した

.github/workflows/ci.yml, generated-api/apis/IntrospectionApi.ts, generated-api/apis/StackApi.ts, package.json
[CIインテグレーションを整える](https://app.asana.com/0/1204548322306328/1205262475436081/f)
[フロントエンド側アプリケーションのCIを整える](https://app.asana.com/0/1204548322306328/1205170770841316/f)
なし
なし
- フロント側のCIを設定した
なし
なし
=> フロント側のCIを設定した

generated-api/apis/IntrospectionApi.ts, generated-api/apis/StackApi.ts, openapi.yml
[本番環境で基本的な機能が使えるようになっている](https://app.asana.com/0/1204548322306328/1205352883161224/f)
[積み上げの反省詳細APIのルーティングを変更する](https://app.asana.com/0/1204548322306328/1205578366702020/f)
本PR
なし
- 反省に関するAPI定義を修正した
- 
-
=> 反省に関するAPI定義を修正した

components/molecules/CheckBoxGroup.tsx, components/molecules/CheckBoxLabel.tsx, components/molecules/FormModal.tsx, components/molecules/LoginForm.tsx, components/molecules/StackList.tsx, components/organisms/DashboardWrapper.tsx, components/organisms/Layout.tsx, components/organisms/MyPageWrapper.tsx, components/uikit/Chart.tsx, config.ts, generated-api/apis/IntrospectionApi.ts, generated-api/apis/StackApi.ts, next.config.js, package-lock.json, pages/index.tsx, types/types.ts, utiliry/session.ts
[本番環境で基本的な機能が使えるようになっている](https://app.asana.com/0/1204548322306328/1205352883161224/f)
[積み上げ時間のグラフを作成する（APIテスト）](https://app.asana.com/0/1204548322306328/1204854764270167/f)
[スキルごとの割合グラフを作成する（APIテスト）](https://app.asana.com/0/1204548322306328/1204854764270172/f)
なし
- スキル一覧のAPI連携
- 積み上げ一覧のAPI連携
- 積み上げ時間と積み上げスキルのグラフのAPI連携
- 反省のAPI連携
なし
=> 積み上げ、スキル、グラフのAPI連携

components/molecules/FormModal.tsx, components/molecules/StackCard.tsx, components/molecules/StackInspectionFormGroup.tsx, components/molecules/StackIntrospectionShowGroup.tsx, components/molecules/StackList.tsx
[本番環境で基本的な機能が使えるようになっている](https://app.asana.com/0/1204548322306328/1205352883161224/f)
[積み上げの反省を更新できるようにする（APIテスト）](https://app.asana.com/0/1204548322306328/1205363737403476/f)
https://github.com/mnmuu8/skill-climbing-frontend/pull/11
https://github.com/mnmuu8/skill-climbing-frontend/pull/32
https://github.com/mnmuu8/skill-climbing-frontend/assets/62938854/36c70384-b90e-43fa-85de-158201b79a48
- 反省情報を更新できるようにした
- エラーハンドリング
- keep, problem, tryの初期表示
- 詳細表示/更新の切り替え
-
=> 反省情報を更新できるようにした

components/molecules/FormModal.tsx, components/molecules/StackIntrospectionShowGroup.tsx, generated-api/.openapi-generator/FILES, generated-api/apis/IntrospectionApi.ts, generated-api/apis/StackApi.ts, generated-api/models/StacksIntrospectionsIntrospectionProblemsInner.ts, generated-api/models/StacksIntrospectionsProblemsProblem.ts, generated-api/models/index.ts, openapi.yml
[ploblem → problemに変換](https://app.asana.com/0/1204548322306328/1205615130080682/f)
- 「ploblem」というスペルミスを正した
- 
-
=> ploblem → problemに変更した

components/molecules/FormModal.tsx, components/molecules/ProfileCard.tsx, components/molecules/StackIntrospectionShowGroup.tsx, components/molecules/UserProfile.tsx, generated-api/apis/IntrospectionApi.ts, generated-api/apis/StackApi.ts, next.config.js, tsconfig.build.json, types/types.ts
[フロントのビルドエラーの修正](https://app.asana.com/0/1204548322306328/1205578366702037/f)
- ビルドエラーの解消
=> generated-apiをbuildの対象外にした

components/molecules/CheckBoxGroup.tsx, components/molecules/FormModal.tsx, components/molecules/LoginForm.tsx, components/molecules/TeamFormGroup.tsx, components/molecules/TeamList.tsx, components/molecules/TeamListItem.tsx, components/molecules/UserFormGroup.tsx, components/organisms/Sidebar.tsx, context/AppContext.tsx, pages/_app.tsx, styles/globals.css, types/types.ts, utiliry/session.ts
[チームを一覧で確認、追加、更新ができる](https://app.asana.com/0/1204548322306328/1205245405097652/f)
[チーム情報を更新することができる](https://app.asana.com/0/1204548322306328/1205459035462988/f)
[チームを新たに作成することができる](https://app.asana.com/0/1204548322306328/1205459035462991/f)
[チーム一覧が確認できるようになっている](https://app.asana.com/0/1204548322306328/1205459035462985/f)
なし
https://github.com/mnmuu8/skill-climbing-frontend/assets/121008362/e59421b5-7f6b-46fd-bd13-d68fdd192582
- チームの確認、追加、更新をできるようにした
- ユーザーのロールを変更できるようにした
なし
なし
=> チームの確認、追加、更新できるようにした

generated-api/apis/OutputApi.ts, openapi.yml
[アウトプット機能が利用できる](https://app.asana.com/0/1204548322306328/1204548322306418/f)
[アウトプット詳細APIを実装する](https://app.asana.com/0/1204548322306328/1205461985753151/f)
なし
- アウトプット詳細APIを定義した
- 
-
=> アウトプット詳細APIを定義した

components/molecules/FormModal.tsx, components/molecules/OutputFormGroup.tsx, components/organisms/Sidebar.tsx, components/templates/OutputsWrapper.tsx, context/FormDataContext.tsx, pages/outputs/index.tsx, types/api.ts, types/context.ts, types/form.ts, utiliry/api/outputs.ts, utiliry/form.ts, utiliry/validator.ts
[アウトプット機能が利用できる](https://app.asana.com/0/1204548322306328/1204548322306418/f)
[アウトプット作成ができるようになる](https://app.asana.com/0/1204548322306328/1205459035463045/f)
なし
- アウトプット作成のAPI実行テスト
- リッチエディタの作成
なし
=> アウトプット作成のAPI実装

pages/outputs/[output].tsx, types/output.ts
[アウトプットに対してコメントできるようになっている](https://app.asana.com/0/1204548322306328/1205461985753154/f)
[アウトプット詳細の下にコメントが表示されていること](https://app.asana.com/0/1204548322306328/1205826687920680/f)
なし
- アウトプットに対するコメントを表示した
- コードを責務ごとに分割すること
- 後にディレクトリ構成変更タスクがあるから、それが終わったら少しずつリファクタリングする。
- 今のコードが`[output].tsx`に集まりすぎとるのは一旦許容する。
-
=> アウトプットに対するコメントを表示した

generated-api/apis/TeamApi.ts, openapi.yml
[ユーザーを新規登録できる](https://app.asana.com/0/1204548322306328/1205544384881385/f)
[招待後に必要なユーザー情報が入力できること](https://app.asana.com/0/1204548322306328/1205826687920701/f)
- チーム詳細APIを定義した
- 
-
=> チーム詳細APIを定義した

pages/users/register.tsx, types/api.ts, types/form.ts, types/user.ts, utiliry/api.ts
[ユーザーを新規登録できる](https://app.asana.com/0/1204548322306328/1205544384881385/f)
[招待後に必要なユーザー情報が入力できること](https://app.asana.com/0/1204548322306328/1205826687920701/f)
https://github.com/mnmuu8/frontend_stack/assets/62938854/ffd0d566-e431-46a4-9d80-ce3c18fcf7e3
- ユーザー登録ページを作成した
- 招待メールから遷移してくる画面だから、emailとteamはすでに入力済みになる。
- 
-
=> ユーザー登録ページを作成した

components/molecules/StackInspectionFormGroup.tsx
[Keep, Problem, Tryの注釈を入れる](https://app.asana.com/0/1204548322306328/1205627542038991/f)
https://github.com/mnmuu8/frontend_stack/assets/62938854/95036659-2ae7-458b-8136-c2dfa2eb3183
- KPTそれぞれの注釈を追加した
- 
-
=> KPTそれぞれの注釈を追加した

components/molecules/FormModal.tsx, components/molecules/SkillInput.tsx, components/molecules/StackCard.tsx, components/molecules/TeamList.tsx, components/organisms/Layout.tsx, components/organisms/Sidebar.tsx, components/templates/DashboardWrapper.tsx, components/templates/MyPageWrapper.tsx, components/uikit/RankTable.tsx, pages/users/register.tsx, types/session.ts, utiliry/api.ts, utiliry/session.ts
[sessionDataが存在するかどうかの確認は共通化する](https://app.asana.com/0/1204548322306328/1205830546071435/f)
- sessionDataが存在するかどうかの確認は共通化した
- 
-
=> sessionDataが存在するかどうかの確認は共通化した

components/molecules/OutputCard.tsx, components/molecules/ProfileCard.tsx, components/molecules/StackCard.tsx, components/molecules/StackList.tsx, components/molecules/TeamList.tsx, components/molecules/TeamListItem.tsx, components/organisms/Header.tsx, components/organisms/Layout.tsx, components/organisms/Sidebar.tsx, components/templates/DashboardWrapper.tsx, components/templates/MyPageWrapper.tsx, components/uikit/RankTable.tsx, context/AppContext.tsx, pages/index.tsx, pages/mypage/index.tsx, pages/outputs/index.tsx, pages/timeline/index.tsx, styles/globals.css, types/context.ts
[マイページの情報を整えてユーザーが自身の情報を管理しやすくする](https://app.asana.com/0/1204548322306328/1205627611446828/f)
[マイページの情報を整えてユーザーが自身の情報を管理しやすくする](https://app.asana.com/0/1204548322306328/1205826687402991/f)
https://github.com/mnmuu8/frontend_stack/assets/121008362/5dfb8c19-84ff-4902-b275-23902163aecd
特になし
- アプリ全体のレイアウト変更
- Asanaに寄せた
- マイページの情報整理
- アウトプット関連のレイアウト変更
- ClassNameの整理
- 取り急ぎ全体レイアウトのリニューアルを実装しただけなので、細々したパーツやコンポーネント化は別途対応予定
- 積み上げの詳細をモーダルで作成予定（積み上げの説明を表示するため）
=> レイアウト全体のリニューアル

components/molecules/StackCard.tsx, components/molecules/StackInspectionFormGroup.tsx, components/molecules/StackList.tsx, components/molecules/TeamListItem.tsx, components/organisms/Header.tsx, components/organisms/Layout.tsx, components/organisms/Sidebar.tsx, components/templates/MyPageWrapper.tsx, context/SnackbarContext.tsx, pages/_app.tsx
[処理が成功した際にアラートを表示する](https://app.asana.com/0/1204548322306328/1205947063398558/f)
- 処理が成功した際にアラートを表示するためのコンテキストを用意した
- それぞれの処理でアラートを表示すること
-
=> 処理が成功した際にアラートを表示するためのコンテキストを用意した

components/molecules/FormModal.tsx, components/organisms/Layout.tsx
[モーダルで[キャンセル]押した場合の挙動を正す](https://app.asana.com/0/1204548322306328/1205627611446822/f)
https://github.com/mnmuu8/frontend_stack/assets/62938854/37f7b17c-bce6-4076-98ee-a9b960aaab28
- モーダル外をクリックした際にもキャンセルできるようにした
- フォームが初期状態の時にモーダルを出さないようにすること
-
=> モーダル外をクリックした際にもキャンセルできるようにした

components/templates/MyPageWrapper.tsx, components/uikit/Chart.tsx, styles/globals.css, types/utils.ts
[スキルランクの色に応じてグラフの色を変更する｜グラフに単位を追加する](https://app.asana.com/0/1204548322306328/1206166932207811/f)
- スキルランクのグラフに注釈とラベルを追加した
- 
-
=> スキルランクのグラフに注釈とラベルを追加した

components/layouts/Header.tsx, features/stacks/components/StackCard.tsx, features/stacks/functions/delete.ts, pages/timeline/index.tsx
[不要なデータを自由に削除できるようにする](https://app.asana.com/0/1204548322306328/1206116612623898/f)
[積み上げを削除できるようにする](https://app.asana.com/0/1204548322306328/1206234783743626/f)
https://github.com/mnmuu8/frontend_stack/assets/62938854/d45d0169-a2cd-49c0-8f5a-a5b98ffec4c0
- 積み上げを削除できるようにした
- 積み上げ一覧が変化するごとにAPIを叩いて最新情報を持ってくるようにした
- 
-
=> 積み上げを削除できるようにした

features/stacks/components/StackCard.tsx, features/teams/components/TeamList.tsx, features/teams/components/TeamListItem.tsx, features/teams/functions/delete.ts
[不要なデータを自由に削除できるようにする](https://app.asana.com/0/1204548322306328/1206116612623898/f)
[チームを削除できるようにする](https://app.asana.com/0/1204548322306328/1206234783743631/f)
https://github.com/mnmuu8/frontend_stack/assets/62938854/cd506e21-ba86-4ef0-b15e-eb1bdd93de66
- チームを削除できるようにした
- 
-
=> チームを削除できるようにした

common/styles/ui-elements/button.css, features/outputs/functions/api.ts, features/outputs/functions/delete.ts, pages/outputs/[output].tsx
[不要なデータを自由に削除できるようにする](https://app.asana.com/0/1204548322306328/1206116612623898/f)
[アウトプットを削除できるようにする](https://app.asana.com/0/1204548322306328/1206234783743634/f)
https://github.com/mnmuu8/frontend_stack/assets/121008362/97aa9135-f500-48bd-b9e1-836b5b2379d3
- アウトプットを削除できるようにした
- 自分のアウトプットのみ削除ボタン表示する
=> アウトプットを削除できるようにした

features/outputs/comments/components/OutputCommentCard.tsx, features/outputs/comments/functions/delete.ts, features/outputs/types/output.ts, pages/outputs/[output].tsx
[不要なデータを自由に削除できるようにする](https://app.asana.com/0/1204548322306328/1206116612623898/f)
[アウトプットに対するコメントを削除できるようにする](https://app.asana.com/0/1204548322306328/1206234783743637/f)
https://github.com/mnmuu8/frontend_stack/assets/121008362/9b9858da-bb21-4771-8fd7-6e9c32ae8434
- アウトプットのコメントを削除できるようにした
- 自分のコメントのみ削除できるようにする
=> アウトプットのコメントに削除機能を追加

common/types/ui-parts/form.ts, components/ui-parts/FormModal.tsx, features/stacks/components/StackCard.tsx, features/stacks/components/StackForm.tsx, features/stacks/functions/api.ts, features/stacks/functions/update.ts, features/stacks/types/api.ts, features/stacks/types/context.ts
[積み上げに対してユーザー自身が自由に操作できる](https://app.asana.com/0/1204548322306328/1206166932207802/f)
[積み上げの更新をできるようにする](https://app.asana.com/0/1204548322306328/1206234783743718/f)
https://github.com/mnmuu8/frontend_stack/assets/62938854/1d681f25-b4d9-418f-9d5e-1ca199e6e29a
- 積み上げを更新できるようにした
- 
-
=> 積み上げを更新できるようにした
